### PR TITLE
Setting version for automatically generated packages

### PR DESCRIPTION
**Pull request by ceball**
Note: changes travis to use tox (and adds appveyor). You may wonder why I would add tox. Tox means:
* commands can be written once and run on appveyor, travis, local machine
* commands can be written once and run in multiple different environments (e.g. different versions of python, different optional dependencies present, etc)
* travis and appveyor config can be small and really only config
* the *built package* gets tested (by default, tox builds and installs the package before testing; tox also supports testing develop install or no install too if you want to test before installing, as if a developer)

However, if you don't want to use tox locally, it's no problem because tox is completely optional: you can run the same commands as before on their own (e.g. nosetests, setup.py, etc), in which case tox.ini could just serve as some documentation for you.

None of the above applies to conda (build), which does not have integrations (that I know of) with tox or travis or appveyor, but is more general than 'just python packaging' and itself promotes some testing as part of the package building process, so partially overlaps with tox in some ways.

Some projects will benefit a lot from tox (e.g. param), whereas others will benefit a lot or only really be practical with conda (e.g. datashader), which is why I've included both here.

### CODE REVIEW

**Comment by jlstevens** [comment]
@ceball This PR should now be ready to test. Note that to update the .version file, you need the output of:

```
git describe --long --match v*.*
```

The suggested workflow has not yet been tested with travis/automation but I have set things up to be automation friendly in autover itself.

**Comment by jlstevens** [comment]
Note that that the version is verified for *releases* (i.e when you use ``python setup.py upload`` where the repo state should not be dirty but this does not apply to conda build. This means there is no issue generating dev/nightly packages for conda.

**Comment by jlstevens** [comment]
@ceball Looks like it is all working now?

**Comment by ceball** [comment]
I don't yet quite understand when to update the .version file. 

I do the following to make "latest master" python and conda packages:
```
git describe --long --match v*.* > autover/.version
python setup.py sdist
conda build conda.recipe/
```

What should I do for a release? I need to update .version, commit, tag, and make the package...but in what order? How does the .version file that I'm committing know what the commit/tag will be?

**Comment by jlstevens** [comment]
> How does the .version file that I'm committing know what the commit/tag will be?

It doesn't. The best thing I can suggest is to disable the check in ``setup.py`` to allow the ``.version`` file to be dirty when doing a release i.e [remove this line](https://github.com/ioam/autover/pull/9/files#diff-2eeaed663bd0d25b7e608891384b7298L46). Then you can update the ``.version`` file and release/upload without trying to make the SHA in the file match match the SHA after it is committed.

If that works, I can think of how to reinstate some sort of checking. I have a few ideas but I want to make sure the basic principle works first.

**Comment by jlstevens** [comment]
Actually, I don't think the check makes sense anymore anyway - there is no explicitly declared version information in the package itself anymore. All the information is obtained from git, i.e via ``git describe`` directly or via ``git describe`` saved to the .version file.

Removing the check means it is now the dev's responsibility to tag things correctly and update ``.version``. What a *new* check *could* do is allow the repo to be dirty but make sure that the SHA in the ``.version`` file matches the output of ``git describe`` to ensure you have updated the file before you upload.

I am happy to implement this idea - if you agree it makes sense...

**Comment by jlstevens** [comment]
Thinking about it more, ``setup.py`` could use ``autover`` to automatically update the ``.version`` file for PyPI releases. You still need to update the ``.version`` file with a separate command for conda packaging unless ``conda build`` has some way to run python code before running a build i.e some sort of 'pre-build hook'.

**Comment by jlstevens** [comment]
To test that tagging generates a release, this PR needs to be merged to master. There are few more small things to do (e.g PEP440 and the extra check) but the system *should* now work.

**Comment by jlstevens** [comment]
One thing to check is that the version built out of templating git describe for conda (meta.yaml) matches the PEP440 format.

**Pull request merged**
