### PR TITLE
Fixed some earlier copy/paste error, which has been causing certain tests to do nothing.

### PR DESCRIPTION
**Pull request by ceball**

### CODE REVIEW

**Comment by jlstevens** [comment]
Oh no! Hope the tests still pass...

**Comment by ceball** [comment]
I think they will - they passed in the past (they were accidentally disabled late on).

**Comment by ceball** [comment]
Ideally we'd use symlinks to avoid duplicating files in the examples, but that will cause us different problems e.g. on windows :( The test files in question are also overly complicated because of the history they've been through, and could be simplified...but don't have time right now.

**Comment by jlstevens** [comment]
> The test files in question are also overly complicated because of the history they've been through, and could be simplified...but don't have time right now.

It probably isn't worth the effort of refactoring unless you foresee more tests that we want to add...

**Pull request merged**
