### PR TITLE
Guess at fixing failing build based on messages from pip.

### PR DESCRIPTION
**Pull request by ceball**
Screenshot from 2020-04-13 20-01-04

(noticed in #59)

### CODE REVIEW

**Comment by ceball** [comment]
This has fixed the build that was failing (for the "example" "pkg_depend" build). 

However, looks like the same error message then appears in a subsequent build (the "example_pipgit" "pkg_depend" build).

Before:

Screenshot from 2020-04-13 20-08-36

After:

Screenshot from 2020-04-13 20-07-55

I haven't looked into the new failure beyond seeing the error message text looked to be the same. I probably won't work more on this PR (and definitely not any more today).

**Comment by ceball** [comment]
I've fixed what I (vaguely) know about:

Screenshot from 2020-04-14 12-44-14

Now fails at downloading miniconda. Has the download url changed?

Screenshot from 2020-04-14 12-44-54

**Comment by jbednar** [comment]
Yes, repo.continuum.io is now repo.anaconda.com; see https://github.com/pyviz-dev/pyctdev/pull/68/files

**Comment by ceball** [comment]
Knowing that the last traces of Continuum are being erased would have been
helpful to know 8 hours ago, thanks 😂

**Comment by jbednar** [comment]
The Distribution team was genuinely surprised to hear that anyone was still using repo.continuum.io...

**Comment by ceball** [comment]
ha ha, continuum lives on:

Screenshot_20200414-223748

**Comment by ceball** [comment]
Lots of travis busywork to do across the world :(

Screenshot_20200414-224832


With e.g. GitHub actions, at least the change would only need to be made once (in an "install miniconda" action, and would then apply to everyone using that action.

**Comment by ceball** [comment]
Maybe the surprise you mention refers to the surprise that people have been reading and following the official docs in the first place?! 😂

Screenshot_20200414-230518~2


(Unless there's some subtlety I haven't noticed, and got wrong myself?)

**Comment by ceball** [comment]
Ah, there is a redirect of some type - the above wget command works for me. 

So the joke is on me; I'm presumably not correctly using whatever python lib I use to download the files.

(Still, seems like the docs should be updated to the new link? Why have everyone going through the redirect? Not totally sure about the new company name? 😂)

**Pull request merged**
