### PR TITLE
Add support for explicit package name

### PR DESCRIPTION
**Pull request by jlstevens**
PR to address #38.

### CODE REVIEW

**Review by jbednar — APPROVED** [review]
Looks good to me.

**Comment by jlstevens** [comment]
Currently some of the tests seems to be failing with:

```
ERROR: toxini file 'tox.ini' not found
```

Which doesn't see related. @ceball any ideas?

**Comment by jlstevens** [comment]
Tests have now passed.

**Comment by ceball** [comment]
@jlstevens I'll shortly want to update your PR here with changes from master. How do you prefer I do that? (merge, rebase, something else?)

**Comment by jlstevens** [comment]
> How do you prefer I do that? (merge, rebase, something else?)

I'm happy if you rebase.

**Comment by jlstevens** [comment]
@ceball Thanks for setting up the new test. It now seems to be passing, so are you happy for me to squash merge now?

**Comment by ceball** [comment]
I'm done now (unless the tests fail)

**Comment by ceball** [comment]
...although I realize now they're going to fail...at least because there'd need to be a new param release for one of the tests.

**Comment by ceball** [comment]
For the embed version tests, how did we do that before? Do I push a new tag and then update the default ref for all the embed_version functions?

**Comment by jlstevens** [comment]
> Do I push a new tag and then update the default ref for all the embed_version functions?

That is the best thing to do till that new version of pip becomes common....

**Comment by ceball** [comment]
Ah, is this why when I currently ask autover for its version, I get 0.2.1.post... rather than 0.2.2.post... - because 0.2.2 is a tag on a commit that never made it to master?

**Comment by ceball** [comment]
Ok, now the tests have passed using tag 0.2.3 (a few commits ago on this branch) and param 1.6.1a0 (https://test.pypi.org/project/param/), I guess the next steps are to release param 1.6.1 (only difference from 1.6.0 is an updated autover) and then update this PR to use param 1.6.1 and then merge this PR to master and then tag autover 0.2.4...?

**Comment by jbednar** [comment]
Sounds good.

**Comment by ceball** [comment]
Decided to get #41 in to 1.6.1 too (important for developers), so just waiting on that.

**Comment by ceball** [comment]
(Oh and I suppose for https://github.com/ioam/param/pull/225 to get officially rejected!)

**Comment by jlstevens** [comment]
The merge conflicts don't look too bad. I'll try resolving them using GitHub's merge tool now...

**Comment by ceball** [comment]
>> @jlstevens I'll shortly want to update your PR here with changes from master. How do you prefer I do that? (merge, rebase, something else?)
>
> I'm happy if you rebase.

I've been rebasing+push forcing in pyviz as requested, but you yourself just merged :) I don't mind which way we do things in pyviz projects, but I do have a preference for consistency...is there a good reason not to do things consistently?

**Comment by jlstevens** [comment]
> ... is there a good reason not to do things consistently?

*Very* occasionally I use the GitHub merge tool if the conflicts are trivial to solve but I *never* do merge commits from my local repo. I wouldn't use the github merge tool for anything complicated  and it has no difference on master as we squash merge the PR in the end anyway.

What is wrong with using whatever is easiest at the time?

**Comment by ceball** [comment]
I'm confused about what is the next step with this PR. 

E.g. looking at this github PR view, I'm confused about what code's actually in this PR now. There seems to be code here now that shouldn't be here, and if it ends up in master, that will be an error. Maybe it won't be merged...not sure what github is tracking...

Is it obvious to you what will happen?

**Comment by jlstevens** [comment]
> Is it obvious to you what will happen?

I'm afraid not but I can assure you the merge I did to resolve conflicts was very simple. From memory it was:

* One block in travis.yaml for a new test condition (mixed case irrc)
* A couple of method signatures due to the addition of ``pkgname``

So it isn't that commit to blame! I'm happy to redo the bits I understand (if necessary) which is up to the third commit ('Updated version.py in pkg_bundle') but after that I don't understand the changes well enough to follow.

**Comment by jlstevens** [comment]
Actually here is the diff of the merge commit: https://github.com/ioam/autover/commit/bd4d648b40ee49d810ab24b4d4ac9d8c076dee86

**Edit**: The conflicts related to the ``version.py`` code I mention above were simple and don't show up as they are now consistent with master. The remaining changes might be wrong though?

**Comment by ceball** [comment]
I'm confused - I'm not sure what your intended approach to getting this onto master is. Unless github tracks something I don't know about (which I would be happy to learn about if so...)?

Otherwise, my approach would now be to revert or drop the merge above and then rebase against master, then press the squash merge button. (After doing the thing I mention [above](https://github.com/ioam/autover/pull/39#issuecomment-383236343) about releasing param etc.)

**Comment by jlstevens** [comment]
Feel free to rebase or change this PR in whatever way makes sense to you.

**Comment by ceball** [comment]
How would you go forward from here normally?

**Comment by jlstevens** [comment]
I get the source of the confusion now...I didn't resolve the conflicts quite right.

**Comment by ceball** [comment]
I think this still isn't quite right, and that trying to correct it manually/by memory is difficult.

**Comment by ceball** [comment]
Actually, it's not far off now. I believe there's just one bogus chunk of code left in:

```
diff --git a/.travis.yml b/.travis.yml
index 5496ad4..a5a1e44 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -213,6 +213,20 @@ jobs:
 
 ##############################
 
+# test that dirty detection works
+
+    - <<: *example_tests
+      python: 3.6
+      env:
+        - DESC="check dirty"
+        - EXAMPLE=pkg_bundle
+        - EXTRA="--dir=/tmp/123"
+      install: true
+      script:
+        - doit $EXTRA check_dirty_detection
+
+##############################
+
```

**Comment by jlstevens** [comment]
> I believe there's just one bogus chunk of code left in

I merged that in assuming it was still needed. I'll remove it now.

**Comment by jlstevens** [comment]
One last test is failing. It seems to be related to [this](https://github.com/ioam/autover/commit/bd4d648b40ee49d810ab24b4d4ac9d8c076dee86#diff-5ddda38bd048b0606552d6c1890f9259L107):

https://travis-ci.org/ioam/autover/jobs/370251858#L526

**Comment by ceball** [comment]
Thanks for sorting that out.

I don't immediately know why that test fails. It passes on master. I'll need to clone and run locally to investigate. But the test's error reporting is definitely not great!

**Comment by jlstevens** [comment]
That last failing test is a total mystery to me and seems to be passing on master. @ceball merge?

**Comment by ceball** [comment]
I can't reproduce that test failure locally. Weird.

So yes, I think we should merge. 

As Jean-Luc pointed out to me, I can merge this PR, then update and release param, and then in a subsequent PR update autover's tests to use the new param.

I'll also first test version.py from param dev release with earthsim, which is where this whole thing originated...

**Comment by jlstevens** [comment]
@ceball It is now passing on master. I just want to add a note that we will need to tag and update the ref for the auto embed stuff...

*Edit*: Just saw your latest commit message on master, looks like you are on the case already!

**Pull request merged**
