### PR TITLE
Changed default policy for dirty repositories to 'report'

### PR DESCRIPTION
**Pull request by jlstevens**
This is a friendlier default e.g for ``python setup.py develop``.

### CODE REVIEW

**Comment by ceball** [comment]
I think `report` is the right default. (I also think `strip` shouldn't exist - or at least, I can't see why I'd want to use it.)

The tests have failed because the version.py files in pkg_bundle and PkgBundle haven't been updated (there's a test checking they're the same as in autover itself, since we can't use symlinks). 

After that, the tests should then fail again, because there's a test that an error is raised on attempting to package a dirty repo. I think that test should be replaced with one that checks the generated package name has `+...-dirty` (or similar) in its name, so that pypi would reject it.

**Comment by jlstevens** [comment]
> I think that test should be replaced with one that checks the generated package name has +...-dirty (or similar) in its name, so that pypi would reject it.

Sounds sensible to me! I assume conda channels *wouldn't* reject such a version?

**Comment by ceball** [comment]
> I assume conda channels wouldn't reject such a version?

I forgot to mention conda: conda packages can't have `-` in the version.

pypi would reject because of `+`.

So `+...-dirty` should be fine for both. I think...we'll see :)

**Comment by ceball** [comment]
Any reason this branch wasn't made from latest master?

**Comment by ceball** [comment]
Hope not, because I just rebased it...

**Comment by ceball** [comment]
If the tests pass, I'm done with this PR and it could be merged from my point of view.

**Pull request merged**
