### PR TITLE
Test against latest param release.

### PR DESCRIPTION
**Pull request by ceball**

### CODE REVIEW

**Comment by jlstevens** [comment]
I guess this PR can be updated again once param 1.6 is released.

**Comment by ceball** [comment]
Yes, sorry, I should have indicated it's not ready for merging yet.

I haven't decided what I want this test to be. A test against param latest master? A test against param latest release? Both?

**Comment by jlstevens** [comment]
In order of priority, I would say:

1. A test against param latest release 
2. Both (more testing is good, also more work to set up!)
3. A test against param latest master

I think a test against the latest param release would be sufficient but if you are happy to set up both types of test, that is good too.

**Comment by jlstevens** [comment]
I've updated the pinning of param. It should continue to work as param 1.6.0 is now on PyPI.

If the tests go green, I assume this is ready to merge?

**Comment by jlstevens** [comment]
Ok. I understand this is using a local param build and not PYPI which is what we want.

**Pull request merged**
